### ISSUE TITLE
fluttercouch not available on pub.dartlang.org

### ISSUE THREAD

**Issue by vishaldhudum** [oltrenuovefrontiere/fluttercouch#6]
Create a new project and add dependencies for fluttercouch in pubspec.yaml.

```
dependencies: 
  fluttercouch: ^0.0.1
```

Error on output panel of VS Code
`Because myapp depends on fluttercouch any which doesn't exist (could not find package fluttercouch at https://pub.dartlang.org), version solving failed.
`

I have cross checked its not available on pub.dartlang.org
I am using Windows 10 x64, with IDE Visual Studio Code.

**Comment by oltrenuovefrontiere** [comment]
Unfortunately Fluttercouch is not yet available on pub.dartlang.org because the current version is in alpha and is lacking the necessary documentation. It will be published on pub.dartlang.org as soon as possible.
In the mean time you can download the repository and use path dependency declaration in pubspec.yaml:
```
dependencies:
    fluttercouch:
      path: // relative or absolute path to the main directory of the downloaded repository
```

**Comment by DhudumVishal** [comment]
Thanks below code worked
```
  fluttercouch: 
    git: 
      url: git://github.com/oltrenuovefrontiere/fluttercouch.git
```

**Comment by oltrenuovefrontiere** [comment]
Fluttercouch is now available on pub.dartlang.org. Check [https://pub.dartlang.org/packages/fluttercouch](https://pub.dartlang.org/packages/fluttercouch) for reference.
